SET TIME ZONE 'America/Bogota';

-- Creación de la tabla TBL_PERSONAS
CREATE TABLE TBL_PERSONAS (
    PER_ID SERIAL NOT NULL,
    PER_NOMBRE VARCHAR(200) NOT NULL,
    PER_TELEFONO VARCHAR(100) NOT NULL,
    PER_EMAIL VARCHAR(100) NOT NULL,
    PER_USUARIO_CREACION VARCHAR(100) NOT NULL,
    PER_FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PERSONAS PRIMARY KEY (PER_ID),
    CONSTRAINT UQ_TBL_PERSONAS_PER_EMAIL UNIQUE (PER_EMAIL)
);

-- Creación de la tabla TBL_USUARIOS
CREATE TABLE TBL_USUARIOS (
    USU_ID SERIAL NOT NULL,
    USU_USERNAME VARCHAR(25) NOT NULL,
    USU_CONTRASENA VARCHAR(100) NOT NULL,
    USU_ROLES VARCHAR(500) NOT NULL,
    USU_ESTADO BOOLEAN NOT NULL,
    USU_INTENTOS INTEGER NOT NULL DEFAULT 0,
    USU_PERSONA_ID INTEGER NOT NULL,
    USU_USUARIO_CREACION VARCHAR(100) NOT NULL,
    USU_FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    CONSTRAINT PK_USUARIOS PRIMARY KEY (USU_ID),
    CONSTRAINT FK_PERSONA_ID FOREIGN KEY (USU_PERSONA_ID) REFERENCES TBL_PERSONAS(PER_ID),
    CONSTRAINT UQ_TBL_USUARIOS_USU_USERNAME UNIQUE (USU_USERNAME),
    CONSTRAINT UQ_TBL_USUARIOS_USU_PERSONA_ID UNIQUE (USU_PERSONA_ID)
);